### ISSUE TITLE
Use ad-hoc test provider to test outcome submission

### ISSUE THREAD

**Issue by your** [ministryofjustice/laa-cwa-feature-tests#76]
Currently, we use a randomly chosen provider/user (for each environment) and it's prone to problems i.e. they get disabled, or the submission period is used already in one specific environment.

We'd have to create scripts to generate test providers in DEV/TST/UAT.

**Comment by solomonahmed** [comment]
To do this requires creating the following entities:-

1. A dummy provider - Records imported into AP_SUPPLIERS_INT and the relevant interface prog run in Oracle
2. Dummy sites for the provider - Records imported into AP_SUPPLIER_SITES_INT and the relevant interface prog run in Oracle
3. Dummy users.  Calls to the fnd_user_pkg.createuser API to create users and calls to the fnd_user_pkg.addresp API to add resp to the users
4. Dummy contracts.  Records imported into PO_HEADERS_INTERFACE to add contract records.

The above steps seem the minimum atm to provide the feature tests with a dummy user.  The .sql scripts could be wrapped in a Python program and associated with this repo perhaps?

**Comment by solomonahmed** [comment]
This should be bumped up the list of priorities.

A recent set of tests I wrote to test magistrate court fees cannot be used with the adhoc provider approach.  This is because the region the provider's office is located in is significant and affects whether certain tests pass validation or not.

At the moment the default position for selecting providers is to select the first one on an environment specific list which matches the area of law of the test.  These are different depending on the env.  In some envs, like TST for example, the first CRIME LOWER provider is based on London, in other envs, like DEV, the first CRIME LOWER provider is based outside of London.  In the mag court fees validation tests the office of the provider is a key influencing factor in determining whether a provider can claim using certain codes e.g. a provider in London cannot claim using PROE or PROF.

The result of the above is tests can pass on DEV which then fail on TST.  Obviously, this is not a desirable situation.

**Comment by solomonahmed** [comment]
Deepak has already completed PoC work to create adhoc providers.  Solomon has create a process to dynamically supply feature tests with providers from an API.  The latter will be progressed via 3 tickets which should go some way to resolving the issue.
https://dsdmoj.atlassian.net/browse/TA-2625
https://dsdmoj.atlassian.net/browse/TA-2626
https://dsdmoj.atlassian.net/browse/TA-2627
